### ISSUE TITLE
Multiple Batteries

### ISSUE THREAD

**Issue by inaimathi** [fukamachi/trivial-battery#2]
`battery-info` has less than ideal behavior on laptops with multiple batteries (since it only seems to return the status of one battery, which may very well be the backup rather than the one currently discharging).

Would you be open to accepting a pull request that:

1. Changes `battery-info` to return a list of batteries or map of battery names to info maps
2. Adds `battery-details` that returns a more extensive list of properties about a particular battery

**Comment by fukamachi** [comment]
Multiple batteries support sounds reasonable and the patch is welcome.

I'm a little bit worry about it's okay for all platforms (Mac OS, Linux and Windows).

**Comment by inaimathi** [comment]
Addressed in https://github.com/pokepay/trivial-battery/commit/9412a1d838c4a1aadfd0e3b24d3b97565a03db9a
